apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q27i21kny-nodejs
  janus-idp.io/tekton: q27i21kny-nodejs
  backstage.io/kubernetes-id: q27i21kny-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q27i21kny-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
