apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: q27i21kny-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q27i21kny-nodejs 
  name: q27i21kny-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: q27i21kny-nodejs 
